"""
Self Calibration from Vanishing Points
--------------------------------------

Estimates camera intrinsic geometry from vanishing points
generated by approximately orthogonal scene directions.

No environment-specific measurements are used.

Important:
This is a projective self-calibration module.
It does NOT by itself recover absolute metres/feet.

Absolute scale is handled separately.
"""

from dataclasses import dataclass
from typing import Optional, List, Tuple
import math

import numpy as np
import cv2


# ============================================================
# DATA STRUCTURES
# ============================================================

@dataclass
class VanishingPoint:
    x: float
    y: float
    support: int
    angle: float


@dataclass
class CalibrationResult:
    success: bool
    focal_length: Optional[float]
    principal_x: float
    principal_y: float
    intrinsic_matrix: Optional[np.ndarray]
    vanishing_points: List[VanishingPoint]
    confidence: float
    message: str


# ============================================================
# BASIC GEOMETRY
# ============================================================

def angle_difference(a, b):

    d = abs(a - b)

    return min(
        d,
        180.0 - d
    )


def line_to_homogeneous(
    x1, y1, x2, y2
):

    p1 = np.array(
        [x1, y1, 1.0],
        dtype=float
    )

    p2 = np.array(
        [x2, y2, 1.0],
        dtype=float
    )

    return np.cross(p1, p2)


def intersect_lines(
    line1,
    line2
):

    point = np.cross(
        line1,
        line2
    )

    if abs(point[2]) < 1e-9:
        return None

    return (
        point[0] / point[2],
        point[1] / point[2]
    )


# ============================================================
# VANISHING POINT FROM LINE GROUP
# ============================================================

def estimate_vanishing_point(
    lines,
    angle_tolerance=5.0
):
    """
    Estimate a vanishing point from approximately parallel
    image lines.

    Uses pairwise intersections followed by a median estimate.
    """

    if len(lines) < 3:
        return None

    intersections = []

    homogeneous_lines = []

    for line in lines:

        x1, y1, x2, y2 = line

        homogeneous_lines.append(
            line_to_homogeneous(
                x1, y1, x2, y2
            )
        )

    for i in range(
        len(homogeneous_lines)
    ):

        for j in range(
            i + 1,
            len(homogeneous_lines)
        ):

            point = intersect_lines(
                homogeneous_lines[i],
                homogeneous_lines[j]
            )

            if point is None:
                continue

            x, y = point

            if (
                math.isfinite(x)
                and
                math.isfinite(y)
            ):

                intersections.append(
                    (x, y)
                )

    if len(intersections) < 3:
        return None

    xs = [
        p[0]
        for p in intersections
    ]

    ys = [
        p[1]
        for p in intersections
    ]

    return (
        float(np.median(xs)),
        float(np.median(ys))
    )


# ============================================================
# GROUP LINES BY DIRECTION
# ============================================================

def group_lines_by_angle(
    lines,
    tolerance=6.0
):

    groups = []

    for line in lines:

        x1, y1, x2, y2 = line

        angle = (
            math.degrees(
                math.atan2(
                    y2 - y1,
                    x2 - x1
                )
            )
            % 180
        )

        assigned = False

        for group in groups:

            if angle_difference(
                angle,
                group["mean_angle"]
            ) <= tolerance:

                group["lines"].append(line)

                angles = []

                for item in group["lines"]:

                    ix1, iy1, ix2, iy2 = item

                    a = (
                        math.degrees(
                            math.atan2(
                                iy2 - iy1,
                                ix2 - ix1
                            )
                        )
                        % 180
                    )

                    angles.append(a)

                group["mean_angle"] = (
                    np.mean(angles)
                )

                assigned = True
                break

        if not assigned:

            groups.append(
                {
                    "mean_angle": angle,
                    "lines": [line]
                }
            )

    groups.sort(
        key=lambda g: len(g["lines"]),
        reverse=True
    )

    return groups


# ============================================================
# DETECT VANISHING POINTS
# ============================================================

def detect_vanishing_points(
    image,
    min_line_length_ratio=0.08
):

    height, width = image.shape[:2]

    gray = cv2.cvtColor(
        image,
        cv2.COLOR_BGR2GRAY
    )

    gray = cv2.GaussianBlur(
        gray,
        (5, 5),
        0
    )

    edges = cv2.Canny(
        gray,
        50,
        150
    )

    minimum_length = max(
        30,
        int(width * min_line_length_ratio)
    )

    raw_lines = cv2.HoughLinesP(
        edges,
        1,
        np.pi / 180,
        threshold=50,
        minLineLength=minimum_length,
        maxLineGap=25
    )

    if raw_lines is None:

        return [], edges

    lines = [
        tuple(
            int(v)
            for v in item[0]
        )
        for item in raw_lines
    ]

    groups = group_lines_by_angle(
        lines
    )

    vanishing_points = []

    for group in groups[:8]:

        if len(group["lines"]) < 3:
            continue

        vp = estimate_vanishing_point(
            group["lines"]
        )

        if vp is None:
            continue

        x, y = vp

        # Reject completely absurd numerical results.
        if (
            abs(x) > width * 100
            or
            abs(y) > height * 100
        ):
            continue

        vanishing_points.append(
            VanishingPoint(
                x=x,
                y=y,
                support=len(group["lines"]),
                angle=group["mean_angle"]
            )
        )

    return vanishing_points, edges


# ============================================================
# PRINCIPAL POINT
# ============================================================

def estimate_principal_point(
    image
):

    height, width = image.shape[:2]

    """
    Initial assumption:
    principal point is close to the optical center.

    This is NOT an airport/environment assumption.
    It is a standard initialization for an uncalibrated camera.

    Later, if enough vanishing-point constraints exist,
    this can be optimized.
    """

    return (
        width / 2.0,
        height / 2.0
    )


# ============================================================
# FOCAL LENGTH FROM ORTHOGONAL VANISHING POINTS
# ============================================================

def focal_length_from_orthogonal_vps(
    vp1,
    vp2,
    principal_x,
    principal_y
):
    """
    For orthogonal directions:

    (v1-c)^T (v2-c) + f^2 = 0

    Therefore:

    f^2 = -(v1-c)^T(v2-c)
    """

    x1 = vp1.x - principal_x
    y1 = vp1.y - principal_y

    x2 = vp2.x - principal_x
    y2 = vp2.y - principal_y

    value = -(
        x1 * x2 +
        y1 * y2
    )

    if value <= 0:
        return None

    return math.sqrt(value)


# ============================================================
# FIND ORTHOGONAL VP PAIRS
# ============================================================

def find_focal_candidates(
    vanishing_points,
    principal_x,
    principal_y
):

    candidates = []

    for i in range(
        len(vanishing_points)
    ):

        for j in range(
            i + 1,
            len(vanishing_points)
        ):

            vp1 = vanishing_points[i]
            vp2 = vanishing_points[j]

            focal = (
                focal_length_from_orthogonal_vps(
                    vp1,
                    vp2,
                    principal_x,
                    principal_y
                )
            )

            if focal is None:
                continue

            support = (
                vp1.support +
                vp2.support
            )

            candidates.append(
                {
                    "focal": focal,
                    "i": i,
                    "j": j,
                    "support": support
                }
            )

    candidates.sort(
        key=lambda x: x["support"],
        reverse=True
    )

    return candidates


# ============================================================
# BUILD CAMERA MATRIX
# ============================================================

def build_intrinsic_matrix(
    focal_length,
    principal_x,
    principal_y
):

    return np.array(
        [
            [
                focal_length,
                0,
                principal_x
            ],
            [
                0,
                focal_length,
                principal_y
            ],
            [
                0,
                0,
                1
            ]
        ],
        dtype=float
    )


# ============================================================
# ROBUST FOCAL ESTIMATION
# ============================================================

def robust_focal_estimate(
    candidates
):

    if not candidates:
        return None, 0.0

    focals = np.array(
        [
            c["focal"]
            for c in candidates
        ],
        dtype=float
    )

    # Remove extreme outliers using median absolute deviation.
    median = np.median(focals)

    deviation = np.abs(
        focals - median
    )

    mad = np.median(
        deviation
    )

    if mad > 1e-9:

        mask = (
            deviation
            <= 3.0 * mad
        )

        filtered = focals[mask]

    else:

        filtered = focals

    if len(filtered) == 0:
        return None, 0.0

    focal = float(
        np.median(filtered)
    )

    agreement = (
        len(filtered)
        /
        len(focals)
    )

    return focal, float(agreement)


# ============================================================
# COMPLETE SELF CALIBRATION
# ============================================================

def self_calibrate(
    image
):

    height, width = image.shape[:2]

    vps, edges = detect_vanishing_points(
        image
    )

    principal_x, principal_y = (
        estimate_principal_point(
            image
        )
    )

    candidates = (
        find_focal_candidates(
            vps,
            principal_x,
            principal_y
        )
    )

    focal, agreement = (
        robust_focal_estimate(
            candidates
        )
    )

    if focal is None:

        return CalibrationResult(
            success=False,
            focal_length=None,
            principal_x=principal_x,
            principal_y=principal_y,
            intrinsic_matrix=None,
            vanishing_points=vps,
            confidence=0.0,
            message=(
                "Could not obtain a valid focal-length "
                "estimate from orthogonal vanishing-point "
                "constraints."
            )
        )

    # Reject implausible numerical solutions.
    if focal < width * 0.05:

        return CalibrationResult(
            success=False,
            focal_length=focal,
            principal_x=principal_x,
            principal_y=principal_y,
            intrinsic_matrix=None,
            vanishing_points=vps,
            confidence=0.0,
            message=(
                "Estimated focal length is numerically "
                "unstable."
            )
        )

    K = build_intrinsic_matrix(
        focal,
        principal_x,
        principal_y
    )

    confidence = min(
        1.0,
        0.5 * agreement +
        0.5 * min(
            1.0,
            len(vps) / 3.0
        )
    )

    return CalibrationResult(
        success=True,
        focal_length=focal,
        principal_x=principal_x,
        principal_y=principal_y,
        intrinsic_matrix=K,
        vanishing_points=vps,
        confidence=confidence,
        message=(
            "Camera intrinsic geometry was estimated "
            "from vanishing-point constraints."
        )
    )


# ============================================================
# DIAGNOSTICS
# ============================================================

def print_calibration_result(
    result
):

    print()
    print("=" * 70)
    print("SELF-CALIBRATION RESULT")
    print("=" * 70)

    print(
        f"Success        : {result.success}"
    )

    print(
        f"Focal length   : {result.focal_length}"
    )

    print(
        f"Principal point: "
        f"({result.principal_x:.2f}, "
        f"{result.principal_y:.2f})"
    )

    print(
        f"VP count       : "
        f"{len(result.vanishing_points)}"
    )

    print(
        f"Confidence     : "
        f"{result.confidence:.2f}"
    )

    print()

    for i, vp in enumerate(
        result.vanishing_points,
        start=1
    ):

        print(
            f"VP {i}: "
            f"x={vp.x:.2f}, "
            f"y={vp.y:.2f}, "
            f"support={vp.support}, "
            f"angle={vp.angle:.2f}"
        )

    print()
    print(result.message)

    print()
    print(
        "IMPORTANT:"
    )

    print(
        "Self-calibration does not establish absolute "
        "metres/feet. Global physical scale is handled "
        "separately."
    )

    print("=" * 70)


# ============================================================
# COMMAND LINE
# ============================================================

if __name__ == "__main__":

    import sys

    if len(sys.argv) < 2:

        print()
        print(
            "Usage:"
        )

        print(
            "py src\\self_calibration.py "
            "path_to_image.jpg"
        )

        print()

        sys.exit(1)

    image_path = sys.argv[1]

    image = cv2.imread(
        image_path
    )

    if image is None:

        raise FileNotFoundError(
            f"Could not read image: {image_path}"
        )

    result = self_calibrate(
        image
    )

    print_calibration_result(
        result
    )